hikmalryvaldi/Techrent

database/migrations/2024_12_01_021407_create_products_table.php, database/migrations/2024_12_01_022925_create_categories_table.php, database/migrations/2024_12_01_023923_create_carousels_table.php, database/migrations/2024_12_01_024927_create_featured_products_table.php
=> Database halaman home

app/View/Components/Navbar.php, resources/views/components/footer.blade.php, resources/views/components/header.blade.php, resources/views/components/navbar.blade.php, resources/views/home.blade.php, resources/views/produk.blade.php, routes/web.php
Halaman produk ditambah revisi navbar
=> HalamanProduk + revisi navbar

app/Http/Controllers/GoogleController.php, composer.json, composer.lock, config/services.php, resources/views/registrasi.blade.php, routes/web.php
Implementasi Login Dengan Google API.
Perubahan : 
- Configurasi Google API pada services.php
- Logik Login dengan Google jika email sudah terdaftar, Buat akun jika email belum terdaftar pada GoogleController
- Perubahan href pada button Login Dengan Google, untuk implementasi Login dengan google
=> Add Google API Login Feature

app/View/Components/Navbar.php, resources/views/components/footer.blade.php, resources/views/components/navbar.blade.php, resources/views/detailProduk.blade.php, resources/views/produk.blade.php, routes/web.php, tailwind.config.js
=> membuat halaman detail Produk

config/services.php, resources/views/registrasi.blade.php
Perubahan :
- Penambahan Button sementara dari backend
- Fitur login X
- Penambahan Client ID dan Secret ID pada services.php
=> Add X or Twitter Login API

config/services.php, resources/views/registrasi.blade.php
Perubahan :
- Penambahan Button sementara dari backend
- Fitur login GitHUb
- Penambahan Client ID dan Secret ID pada services.php
=> Api login GitHub

app/Http/Controllers/HomeController.php, resources/views/components/navbar.blade.php, routes/web.php
mengerjakan live search di halaman home
=> live search home

routes/web.php
=> fitur register

resources/views/components/navbar.blade.php
=> fitur logout

app/Http/Controllers/RegisterController.php, resources/views/auth/index.blade.php
Perubahan : 
- Mengganti logika pada confirm_password menjadi **same:password** agar sama dengan password menggunakan fitur **"confirmed"** laravel
- Menghapus confirmed_password dari tabel user
=> Fixing confirmation password on registration

app/Http/Controllers/SocialiteController.php, database/migrations/0001_01_01_000000_create_users_table.php
Perubahan :
- Perbaikan nama field dalam insert pada SocialiteController.php
- Mengganti phone dalam insert pada SocialiteController.php menjadi null
- Mengganti phone menjadi nullable dalam users migration
=> Fixing insert on Api Login and removing phone value

app/Http/Controllers/SocialiteController.php
Perubahan : 
- Mengganti logic pengkondisian, jika **provider id** yang digunakan oleh login **sama** dengan **provider id** di tabel user, maka user ter **auth** untuk login
=> Fixing API login logic

resources/views/Admin/dasboard.blade.php, resources/views/components/header.blade.php, resources/views/components/sidebar.blade.php, routes/web.php
=> Halaman Admin #Dasboard

resources/views/components/header.blade.php, resources/views/user/profile.blade.php
Perubahan : 
- Penambahan library pada **header** untuk menampilkan **OpenStreetMap**
- Penambahan fitur **OpenStreetMap** menggunakan library **leaflet** untuk **auto input** alamat pada profile **user**
=> Adding OpenStreetMap for Address auto input

app/Http/Controllers/RegisterController.php, database/migrations/0001_01_01_000000_create_users_table.php, resources/views/Admin/dasboard.blade.php, resources/views/Admin/produk.blade.php, resources/views/components/speedDeal.blade.php, routes/web.php
=> Upload Halaman Produk Admin

resources/views/Admin/dashboard.blade.php, resources/views/Admin/produk.blade.php, resources/views/Admin/tambahProduk.blade.php, resources/views/components/footer.blade.php, routes/web.php
=> Add Produk

app/Models/User.php, database/migrations/0001_01_01_000000_create_users_table.php, database/seeders/AdminSeeder.php, database/seeders/DatabaseSeeder.php
Perubahan :
- Menambahkan seeder untuk default admin
- Menambahkan is_admin di tabel user
=> Adding admin seeder & is_admin on users table

resources/views/Admin/produk.blade.php, resources/views/Admin/tambahProduk.blade.php
=> Edit Produk

routes/web.php
=> halaman Users

app/Http/Controllers/ProductAdminController.php, app/Models/Image.php, app/Models/Product.php, database/migrations/2024_12_01_021407_create_products_table.php, database/migrations/2024_12_14_171611_create_images_table.php, database/seeders/ProductSeeder.php, resources/views/Admin/tambahProduk.blade.php, resources/views/components/navbar.blade.php, routes/web.php
mengerjakan fitur tambah produk
=> fitur tambah produk

resources/views/components/navbar.blade.php, resources/views/keranjang.blade.php
=> Halaman Keranjang

resources/views/home.blade.php
=> Revisi FAQ

app/Http/Controllers/NewsletterController.php, app/Mail/Newsletter.php, app/Models/Subscriber.php, database/migrations/2024_12_15_015726_create_subscribers_table.php, resources/views/Admin/newsletter.blade.php, resources/views/components/footer.blade.php, resources/views/components/sidebar.blade.php, resources/views/mail/newsletter.blade.php, routes/web.php
Perubahan : 
- Menambahkan tabel subsribers ke database untuk menyimpan email yang terdaftar lewat newsletter input yang ada di footer
- Menambahkan **NewsletterController**
- Kelas Subscribe untuk menambahkan email ke database tabel subscribers
- Kelas Newsletter untuk mengirimkan email ke semua email yang ada di tabel subscribers
- Menabahkan tampilan newsletter di dashboard admin untuk pesan "Message" yang akan dikirimkan ke email subscribers
=> Adding newsletter feature for subscribed email

resources/views/Admin/dashboard.blade.php, resources/views/Admin/diskon.blade.php, resources/views/components/sidebar.blade.php, routes/web.php
=> Halaman Diskon Produk

resources/views/Admin/diskon.blade.php, resources/views/Admin/voucher.blade.php, resources/views/components/navbar.blade.php, resources/views/components/sidebar.blade.php, resources/views/produk/index.blade.php, routes/web.php
=> Halaman Voucher

app/Http/Controllers/ProductAdminController.php, resources/views/Admin/produk.blade.php, resources/views/Admin/tambahProduk.blade.php
=> revisi fitur tambah produk

resources/views/Admin/perluDikirim.blade.php, resources/views/components/menuPesanan.blade.php, routes/web.php
=> halaman Perlu Dikirim

app/Http/Controllers/ProdukController.php, resources/views/components/navbar.blade.php, resources/views/produk/index.blade.php, routes/web.php
mengerjakan live search halaman produk
=> live search halaman produk

resources/views/Admin/dikirim.blade.php, resources/views/components/menuPesanan.blade.php, routes/web.php
=> Halaman Dikirim

resources/views/Admin/mSelesai.blade.php, resources/views/Admin/mdikirim.blade.php, resources/views/Admin/mpengembalian.blade.php, resources/views/Admin/mperluDikirim.blade.php, resources/views/Admin/mpesananSemua.blade.php, resources/views/components/pesanan.blade.php, routes/web.php
Sudah kang hikmal ada tambahan fitur
=> Fitur di halaman pesanan(Admin)

app/Http/Controllers/ProductAdminController.php, resources/views/Admin/produk.blade.php, routes/web.php
=> fitur edit produk

app/Http/Controllers/ProductAdminController.php, resources/views/Admin/produk.blade.php, routes/web.php
mengerjakan fitur hapus produk
=> fitur hapus produk

resources/views/auth/lupaPassword.blade.php, resources/views/auth/ubahLupaPassword.blade.php
=> Mengubah halaman lupa password

resources/views/auth/index.blade.php, resources/views/user/profile.blade.php
ngubah ikon login dan perbaikan API map
=> Perbaikan API map pada halaman profile dan Perbaikan halaman login

app/Http/Controllers/NewsletterController.php, resources/views/Admin/nNewsletterDiskon.blade.php, resources/views/Admin/produk.blade.php, routes/web.php
mengerjakan liveSearch newsletterdiskon
=> live search newsletterdiskon

resources/views/components/navbar.blade.php, resources/views/produk/index.blade.php
keterangan 
- menambahkan jumlah sewa pada produk
- mencoba update bagian button keranjang
=> perbaikan UI

app/Http/Controllers/DiskonAdminController.php, resources/views/Admin/diskon.blade.php, resources/views/Admin/partials/partialdiskon.blade.php, routes/web.php
mengerjakan fitur halaman diskon
=> fitur halaman diskon

app/Http/Controllers/ProductAdminController.php, composer.json, composer.lock, resources/views/components/speedDeal.blade.php, routes/web.php
mengerjakan fitur pdf reporting
=> fitur pdf reporting

app/Http/Controllers/CartController.php, app/Http/Controllers/CheckoutController.php, app/Http/Controllers/PaymentController.php, app/Models/CartItem.php, composer.json, composer.lock, config/services.php, database/migrations/2024_12_27_114302_create_cart_items_table.php, resources/views/components/navbar.blade.php, resources/views/components/pDetailProComponen.blade.php, resources/views/keranjang.blade.php, resources/views/produk/detailProduk.blade.php, routes/web.php
I dont know what to write anymore im tired
=> Payment gateway

app/Http/Controllers/ProductAdminController.php, resources/views/Admin/dashboard.blade.php, resources/views/Admin/diskon.blade.php, resources/views/Admin/nNewsletterCustom.blade.php, resources/views/Admin/nNewsletterDiskon.blade.php, resources/views/Admin/tambahProduk.blade.php, resources/views/components/speedDeal.blade.php
mengerjakan fitur mengelola image
=> mengelola image

app/Http/Controllers/DetailProdukController.php, resources/views/components/pDetailProComponen.blade.php, resources/views/produk/detailProduk.blade.php, routes/produk.php
=> fitur Cek Ongkir

resources/views/Admin/mpengembalianSelesai.blade.php, resources/views/produk/detailProduk.blade.php
=> menambahkan halaman pengembalian selesai dan perbaikan dalam Payment

app/Http/Controllers/NewsletterController.php, app/Mail/Newsletter.php, app/Models/Carousel.php, app/Models/Product.php, database/seeders/CarouselsSeeder.php, database/seeders/DatabaseSeeder.php, resources/views/Admin/nNewsletterCustom.blade.php, resources/views/Admin/nNewsletterDiskon.blade.php, resources/views/Admin/tambahProduk.blade.php, resources/views/home.blade.php, resources/views/mail/newsletter.blade.php, routes/admin.php, routes/web.php
=> fitur diskon dan revisi home

app/Http/Controllers/NewsletterController.php, app/Mail/Newsletter.php, resources/views/Admin/diskon.blade.php, resources/views/Admin/partials/partialproduk.blade.php, resources/views/Admin/produk.blade.php, resources/views/home.blade.php, resources/views/produk/detailProduk.blade.php, resources/views/produk/index.blade.php
=> fix diskon dan gambar
